"use client";

import { useState } from "react";
import { format } from "date-fns";
import { toast } from "sonner";
import { Bell, Building2, CheckCircle2, ChevronDown, CreditCard, Download, Landmark, Loader2, Receipt, Smartphone, Wallet } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { EmptyState, PageHeader, Panel, SourceBadge, StatCard } from "@/components/page";
import { Pill } from "@/components/status";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { useNow } from "@/hooks/use-now";
import { remindDefaulters } from "@/lib/actions";
import { useBills } from "@/lib/data";
import { inr, relativeDay } from "@/lib/format";
import { sendMaintenanceLive } from "@/lib/live";
import { pointsToast } from "@/lib/notify";
import { useDemoState } from "@/lib/store";
import { cn } from "@/lib/utils";
import type { MaintenanceBill, Resident } from "@/lib/types";

const METHODS = [
  { id: "UPI", label: "UPI", hint: "GPay, PhonePe, Paytm", icon: Smartphone },
  { id: "Card", label: "Card", hint: "Credit or debit", icon: CreditCard },
  { id: "Net banking", label: "Net banking", hint: "All major banks", icon: Landmark },
];

const esc = (s: string) => s.replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]!);

/** Opens a print-ready receipt in a new tab (users can save it as PDF from the print dialog). */
function openReceipt(b: MaintenanceBill, r: Resident) {
  const rows = b.breakdown.map((l) => `<tr><td>${esc(l.label)}</td><td class="r">${inr(l.amount)}</td></tr>`).join("");
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>Receipt ${esc(b.billId)}</title>
<style>body{font:14px/1.5 system-ui,sans-serif;color:#18181b;max-width:640px;margin:40px auto;padding:0 24px}
h1{font-size:20px;margin:0}small{color:#71717a}table{width:100%;border-collapse:collapse;margin:20px 0}
td,th{padding:8px 0;border-bottom:1px solid #e4e4e7;text-align:left}.r{text-align:right}
.tot td{font-weight:700;border-bottom:2px solid #18181b}.paid{display:inline-block;padding:2px 10px;border:1px solid #16a34a;color:#16a34a;border-radius:99px;font-size:12px;font-weight:600}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:4px 24px;margin-top:20px}button{margin-top:24px;padding:8px 16px}@media print{button{display:none}}</style></head>
<body><h1>${esc(r.society)}</h1><small>Maintenance receipt · generated by NexGate</small>
<div class="grid"><div><small>Receipt no.</small><br>REC-${esc(b.billId.toUpperCase())}</div><div><small>Status</small><br><span class="paid">PAID</span></div>
<div><small>Flat</small><br>Tower ${esc(b.block)}, Flat ${esc(b.flat)}</div><div><small>Resident</small><br>${esc(b.residentName)}</div>
<div><small>Billing period</small><br>${esc(b.month)} ${b.year}</div><div><small>Paid on</small><br>${b.paidAt ? format(new Date(b.paidAt), "d MMM yyyy, h:mm a") : "—"}</div>
<div><small>Method</small><br>${esc(b.method ?? "—")}</div><div><small>Transaction ID</small><br>${esc(b.txnId ?? "—")}</div></div>
<table><tr><th>Item</th><th class="r">Amount</th></tr>${rows}<tr class="tot"><td>Total paid</td><td class="r">${inr(b.amount)}</td></tr></table>
<small>This is a computer-generated receipt and does not need a signature.</small><br><button onclick="print()">Print / save as PDF</button></body></html>`;
  const url = URL.createObjectURL(new Blob([html], { type: "text/html" }));
  const win = window.open(url, "_blank", "noopener");
  if (!win) {
    const a = document.createElement("a");
    a.href = url;
    a.download = `Receipt-${b.month}-${b.year}.html`;
    a.click();
  }
  setTimeout(() => URL.revokeObjectURL(url), 60_000);
}

function exportCsv(bills: MaintenanceBill[]) {
  const header = ["Tower", "Flat", "Resident", "Phone", "Period", "Amount", "Status", "Paid on", "Method"];
  const lines = bills.map((b) =>
    [b.block, b.flat, b.residentName, b.phone, `${b.month} ${b.year}`, b.amount, b.paidAt ? "Paid" : "Unpaid", b.paidAt ? format(new Date(b.paidAt), "yyyy-MM-dd") : "", b.method ?? ""]
      .map((v) => `"${String(v).replace(/"/g, '""')}"`)
      .join(","),
  );
  const url = URL.createObjectURL(new Blob([[header.join(","), ...lines].join("\n")], { type: "text/csv" }));
  const a = document.createElement("a");
  a.href = url;
  a.download = `maintenance-ledger-${format(new Date(), "yyyy-MM-dd")}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

export default function MaintenancePage() {
  return (
    <AppShell>
      <Maintenance />
    </AppShell>
  );
}

function Maintenance() {
  const now = useNow(60_000);
  const { resident } = useDemoState();
  const data = useBills();
  const [tab, setTab] = useState<"dues" | "history" | "society">("dues");
  const [paying, setPaying] = useState<MaintenanceBill | null>(null);
  const [expanded, setExpanded] = useState<string | null>(null);

  const unpaid = data.myBills.filter((b) => !b.paidAt).sort((a, b) => a.dueDate.localeCompare(b.dueDate));
  const paid = data.myBills.filter((b) => b.paidAt).sort((a, b) => b.paidAt!.localeCompare(a.paidAt!));
  const outstanding = unpaid.reduce((s, b) => s + b.amount, 0);
  const paidThisYear = paid.filter((b) => new Date(b.paidAt!).getFullYear() === new Date(now).getFullYear()).reduce((s, b) => s + b.amount, 0);
  const onTime = paid.filter((b) => new Date(b.paidAt!).getTime() <= new Date(b.dueDate).getTime()).length;

  const tabs = [
    { id: "dues" as const, label: `Dues (${unpaid.length})` },
    { id: "history" as const, label: `Receipts (${paid.length})` },
    ...(resident.isAdmin ? [{ id: "society" as const, label: "Society ledger" }] : []),
  ];

  return (
    <>
      <PageHeader
        title="Maintenance"
        description="Monthly dues for your flat, payment receipts and — for committee members — the society ledger."
        badge={<SourceBadge live={data.live} error={data.error} />}
      />

      <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
        <StatCard
          label="Outstanding"
          value={outstanding ? inr(outstanding) : "Nothing due"}
          hint={unpaid[0] ? `${unpaid.length} bill${unpaid.length > 1 ? "s" : ""} · next due ${relativeDay(unpaid[0].dueDate, now).toLowerCase()}` : "You're all caught up"}
          icon={Wallet}
          tone={outstanding ? "warning" : "success"}
        />
        <StatCard label={`Paid in ${new Date(now).getFullYear()}`} value={inr(paidThisYear)} hint={`${paid.length} receipt${paid.length === 1 ? "" : "s"}`} icon={Receipt} />
        <StatCard label="On-time payments" value={`${onTime}/${paid.length}`} hint="Paying before the due date earns 50 points" icon={CheckCircle2} tone="success" />
      </div>

      <div className="flex flex-wrap gap-1.5" role="tablist">
        {tabs.map((t) => (
          <button
            key={t.id}
            type="button"
            role="tab"
            aria-selected={tab === t.id}
            onClick={() => setTab(t.id)}
            className={cn(
              "rounded-md px-3 py-1.5 text-xs font-medium transition-colors",
              tab === t.id ? "bg-zinc-900 text-white dark:bg-zinc-100 dark:text-zinc-900" : "border border-zinc-200 bg-white text-zinc-600 hover:border-zinc-300 dark:border-zinc-800 dark:bg-zinc-900 dark:text-zinc-400",
            )}
          >
            {t.label}
          </button>
        ))}
      </div>

      {tab === "dues" &&
        (data.loading ? (
          <p className="text-xs text-zinc-500">Loading bills…</p>
        ) : unpaid.length === 0 ? (
          <EmptyState icon={CheckCircle2} title="All dues cleared" description="No outstanding maintenance for your flat. Receipts are under the Receipts tab." />
        ) : (
          <ul className="space-y-3">
            {unpaid.map((b) => {
              const overdue = new Date(b.dueDate).getTime() < now;
              const open = expanded === b.billId;
              return (
                <li key={b.billId} className={cn("rounded-lg border bg-white dark:bg-zinc-900", overdue ? "border-red-300 dark:border-red-900/60" : "border-zinc-200 dark:border-zinc-800")}>
                  <div className="flex flex-col gap-4 p-4 sm:flex-row sm:items-center sm:justify-between">
                    <div>
                      <div className="flex flex-wrap items-center gap-2">
                        <span className="font-semibold">
                          {b.month} {b.year}
                        </span>
                        {overdue ? <Pill tone="red">Overdue</Pill> : <Pill tone="amber">Due {relativeDay(b.dueDate, now).toLowerCase()}</Pill>}
                      </div>
                      <p className="mt-0.5 text-xs text-zinc-500 dark:text-zinc-400">
                        Tower {b.block}, Flat {b.flat} · due {format(new Date(b.dueDate), "d MMM yyyy")}
                      </p>
                      <button
                        type="button"
                        onClick={() => setExpanded(open ? null : b.billId)}
                        aria-expanded={open}
                        className="mt-1 inline-flex items-center gap-1 text-xs text-zinc-600 hover:underline dark:text-zinc-300"
                      >
                        What&apos;s included <ChevronDown className={cn("h-3 w-3 transition-transform", open && "rotate-180")} />
                      </button>
                    </div>
                    <div className="flex items-center gap-4">
                      <span className="text-xl font-semibold tabular-nums">{inr(b.amount)}</span>
                      <Button onClick={() => setPaying(b)} className="h-9">
                        Pay now
                      </Button>
                    </div>
                  </div>
                  {open && (
                    <dl className="space-y-1 border-t border-zinc-100 px-4 py-3 text-xs dark:border-zinc-800">
                      {b.breakdown.map((l) => (
                        <div key={l.label} className="flex justify-between">
                          <dt className="text-zinc-500 dark:text-zinc-400">{l.label}</dt>
                          <dd className="tabular-nums">{inr(l.amount)}</dd>
                        </div>
                      ))}
                    </dl>
                  )}
                </li>
              );
            })}
          </ul>
        ))}

      {tab === "history" &&
        (paid.length === 0 ? (
          <EmptyState icon={Receipt} title="No receipts yet" />
        ) : (
          <Panel bodyClassName="p-0 overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="text-xs">Period</TableHead>
                  <TableHead className="text-xs">Amount</TableHead>
                  <TableHead className="text-xs">Paid on</TableHead>
                  <TableHead className="hidden text-xs sm:table-cell">Method</TableHead>
                  <TableHead className="text-right text-xs">Receipt</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {paid.map((b) => (
                  <TableRow key={b.billId}>
                    <TableCell className="text-xs font-medium">
                      {b.month} {b.year}
                      {new Date(b.paidAt!).getTime() <= new Date(b.dueDate).getTime() && <Pill tone="emerald" className="ml-2">On time</Pill>}
                    </TableCell>
                    <TableCell className="text-xs tabular-nums">{inr(b.amount)}</TableCell>
                    <TableCell className="text-xs text-zinc-500">{format(new Date(b.paidAt!), "d MMM yyyy")}</TableCell>
                    <TableCell className="hidden text-xs text-zinc-500 sm:table-cell">{b.method ?? "—"}</TableCell>
                    <TableCell className="text-right">
                      <Button variant="ghost" size="sm" className="h-7 gap-1 text-xs" onClick={() => openReceipt(b, resident)}>
                        <Download className="h-3.5 w-3.5" /> Receipt
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </Panel>
        ))}

      {tab === "society" && resident.isAdmin && <SocietyLedger bills={data.society} live={data.live} onRaised={data.refresh} />}

      <PayDialog bill={paying} onClose={() => setPaying(null)} pay={data.pay} live={data.live} onReceipt={(b) => openReceipt(b, resident)} />
    </>
  );
}

function PayDialog({
  bill,
  onClose,
  pay,
  live,
  onReceipt,
}: {
  bill: MaintenanceBill | null;
  onClose: () => void;
  pay: ReturnType<typeof useBills>["pay"];
  live: boolean;
  onReceipt: (b: MaintenanceBill) => void;
}) {
  const [method, setMethod] = useState("UPI");
  const [stage, setStage] = useState<"choose" | "processing" | "done">("choose");
  const [receipt, setReceipt] = useState<MaintenanceBill | null>(null);

  const close = () => {
    onClose();
    setTimeout(() => {
      setStage("choose");
      setReceipt(null);
    }, 200);
  };

  const submit = async () => {
    if (!bill) return;
    setStage("processing");
    try {
      if (!live) await new Promise((r) => setTimeout(r, 1200)); // simulated gateway round-trip
      const res = await pay(bill, method);
      setReceipt(res?.bill ?? bill);
      setStage("done");
      pointsToast(res?.points ?? 0, `Paid ${bill.month} maintenance`);
    } catch (e) {
      setStage("choose");
      toast.error("Payment not completed", { description: e instanceof Error ? e.message : undefined });
    }
  };

  return (
    <Dialog open={!!bill} onOpenChange={(o) => !o && stage !== "processing" && close()}>
      <DialogContent className="max-w-md">
        {stage === "done" && receipt ? (
          <div className="space-y-4 py-2 text-center">
            <CheckCircle2 className="mx-auto h-12 w-12 text-emerald-600" />
            <div>
              <DialogTitle className="text-lg">Payment successful</DialogTitle>
              <DialogDescription className="mt-1">
                {inr(receipt.amount)} for {receipt.month} {receipt.year}
                {receipt.txnId && <span className="block font-mono text-xs">{receipt.txnId}</span>}
              </DialogDescription>
            </div>
            <div className="flex justify-center gap-2">
              <Button variant="outline" onClick={() => onReceipt(receipt)} className="gap-1.5">
                <Download className="h-4 w-4" /> Receipt
              </Button>
              <Button onClick={close}>Done</Button>
            </div>
          </div>
        ) : (
          <>
            <DialogHeader>
              <DialogTitle>Pay maintenance</DialogTitle>
              <DialogDescription>
                {bill && `${bill.month} ${bill.year} · Tower ${bill.block}, Flat ${bill.flat}`}
              </DialogDescription>
            </DialogHeader>
            {bill && (
              <div className="space-y-4">
                <dl className="space-y-1 rounded-md bg-zinc-50 p-3 text-xs dark:bg-zinc-800/50">
                  {bill.breakdown.map((l) => (
                    <div key={l.label} className="flex justify-between">
                      <dt className="text-zinc-500 dark:text-zinc-400">{l.label}</dt>
                      <dd className="tabular-nums">{inr(l.amount)}</dd>
                    </div>
                  ))}
                  <div className="flex justify-between border-t border-zinc-200 pt-1.5 text-sm font-semibold dark:border-zinc-700">
                    <dt>Total</dt>
                    <dd className="tabular-nums">{inr(bill.amount)}</dd>
                  </div>
                </dl>
                {live ? (
                  <p className="text-xs text-zinc-500 dark:text-zinc-400">You&apos;ll complete the payment securely in Razorpay checkout.</p>
                ) : (
                  <fieldset className="space-y-2">
                    <legend className="mb-2 text-xs font-medium">Payment method</legend>
                    {METHODS.map((m) => (
                      <label
                        key={m.id}
                        className={cn(
                          "flex cursor-pointer items-center gap-3 rounded-md border p-3 transition-colors",
                          method === m.id ? "border-zinc-900 dark:border-zinc-100" : "border-zinc-200 hover:border-zinc-300 dark:border-zinc-700",
                        )}
                      >
                        <input type="radio" name="method" value={m.id} checked={method === m.id} onChange={() => setMethod(m.id)} className="sr-only" />
                        <m.icon className="h-4 w-4 text-zinc-500" />
                        <span className="text-sm font-medium">{m.label}</span>
                        <span className="ml-auto text-xs text-zinc-500">{m.hint}</span>
                      </label>
                    ))}
                    <p className="text-[11px] text-zinc-400">Demo mode — no money moves. Live sessions use Razorpay.</p>
                  </fieldset>
                )}
              </div>
            )}
            <DialogFooter className="gap-2 sm:gap-0">
              <Button variant="outline" onClick={close} disabled={stage === "processing"}>
                Cancel
              </Button>
              <Button onClick={submit} disabled={stage === "processing"} className="min-w-32">
                {stage === "processing" ? (
                  <>
                    <Loader2 className="mr-1.5 h-4 w-4 animate-spin" /> Processing…
                  </>
                ) : live ? (
                  "Pay with Razorpay"
                ) : (
                  `Pay ${bill ? inr(bill.amount) : ""}`
                )}
              </Button>
            </DialogFooter>
          </>
        )}
      </DialogContent>
    </Dialog>
  );
}

function SocietyLedger({ bills, live, onRaised }: { bills: MaintenanceBill[]; live: boolean; onRaised: () => void }) {
  const [filter, setFilter] = useState<"unpaid" | "all">("unpaid");
  const [raise, setRaise] = useState({ amount: "2400", month: format(new Date(), "MMMM"), year: String(new Date().getFullYear()) });
  const [raising, setRaising] = useState(false);

  // Demo ledger shows the current billing cycle; live ledger only has unpaid rows from the API.
  const cycleOf = (b: MaintenanceBill) => b.year * 12 + new Date(`${b.month} 1, ${b.year}`).getMonth();
  const latest = Math.max(0, ...bills.map(cycleOf));
  const cycle = live ? bills : bills.filter((b) => cycleOf(b) === latest);
  const collected = cycle.filter((b) => b.paidAt);
  const pending = cycle.filter((b) => !b.paidAt);
  const rows = (filter === "unpaid" ? pending : cycle).sort((a, b) => `${a.block}${a.flat}`.localeCompare(`${b.block}${b.flat}`));
  const pct = cycle.length ? Math.round((collected.length / cycle.length) * 100) : 0;

  return (
    <div className="space-y-4">
      {!live && (
        <Panel title={`${cycle[0]?.month ?? ""} ${cycle[0]?.year ?? ""} collection`} description={`${collected.length} of ${cycle.length} flats paid · ${inr(pending.reduce((s, b) => s + b.amount, 0))} pending`}>
          <Progress value={pct} className="h-2" aria-label="Collection progress" />
          <p className="mt-1.5 text-xs text-zinc-500">{pct}% collected</p>
        </Panel>
      )}

      {live && (
        <Panel title="Raise bills for all flats" description="Creates a maintenance bill for every room and notifies the residents.">
          <form
            className="flex flex-wrap items-end gap-3"
            onSubmit={async (e) => {
              e.preventDefault();
              setRaising(true);
              try {
                await sendMaintenanceLive(Number(raise.amount), raise.month, raise.year);
                toast.success("Bills raised", { description: `${raise.month} ${raise.year} · ${inr(Number(raise.amount))} per flat` });
                onRaised();
              } catch (err) {
                toast.error("Couldn't raise bills", { description: err instanceof Error ? err.message : undefined });
              } finally {
                setRaising(false);
              }
            }}
          >
            <div className="space-y-1">
              <Label htmlFor="rb-amount" className="text-xs">Amount (₹)</Label>
              <Input id="rb-amount" type="number" min={1} className="w-28" value={raise.amount} onChange={(e) => setRaise({ ...raise, amount: e.target.value })} />
            </div>
            <div className="space-y-1">
              <Label htmlFor="rb-month" className="text-xs">Month</Label>
              <Input id="rb-month" className="w-32" value={raise.month} onChange={(e) => setRaise({ ...raise, month: e.target.value })} />
            </div>
            <div className="space-y-1">
              <Label htmlFor="rb-year" className="text-xs">Year</Label>
              <Input id="rb-year" className="w-20" value={raise.year} onChange={(e) => setRaise({ ...raise, year: e.target.value })} />
            </div>
            <Button type="submit" disabled={raising || !Number(raise.amount)}>
              {raising ? "Raising…" : "Raise bills"}
            </Button>
          </form>
        </Panel>
      )}

      <Panel
        title="Flat-wise status"
        action={
          <div className="flex flex-wrap items-center gap-1.5">
            {!live && (
              <>
                <Button size="sm" variant={filter === "unpaid" ? "default" : "outline"} className="h-7 text-xs" onClick={() => setFilter("unpaid")}>
                  Unpaid
                </Button>
                <Button size="sm" variant={filter === "all" ? "default" : "outline"} className="h-7 text-xs" onClick={() => setFilter("all")}>
                  All
                </Button>
              </>
            )}
            <Button size="sm" variant="outline" className="h-7 gap-1 text-xs" onClick={() => exportCsv(cycle)}>
              <Download className="h-3 w-3" /> CSV
            </Button>
            {!live && (
              <Button
                size="sm"
                variant="outline"
                className="h-7 gap-1 text-xs"
                disabled={!pending.length}
                onClick={() => {
                  const n = remindDefaulters();
                  toast.success(`Reminders sent to ${n} flat${n === 1 ? "" : "s"}`, { description: "Residents get an app notification and SMS." });
                }}
              >
                <Bell className="h-3 w-3" /> Remind unpaid
              </Button>
            )}
          </div>
        }
        bodyClassName="p-0 overflow-x-auto"
      >
        {rows.length === 0 ? (
          <EmptyState icon={Building2} title={filter === "unpaid" ? "Everyone has paid" : "No bills"} className="border-0" />
        ) : (
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="text-xs">Flat</TableHead>
                <TableHead className="text-xs">Resident</TableHead>
                <TableHead className="text-xs">Amount</TableHead>
                <TableHead className="text-xs">Status</TableHead>
                <TableHead className="hidden text-xs sm:table-cell">Contact</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {rows.map((b) => (
                <TableRow key={b.billId}>
                  <TableCell className="text-xs font-medium">
                    {b.block}-{b.flat}
                  </TableCell>
                  <TableCell className="text-xs">{b.residentName}</TableCell>
                  <TableCell className="text-xs tabular-nums">{inr(b.amount)}</TableCell>
                  <TableCell>
                    {b.paidAt ? (
                      <Pill tone="emerald">Paid {format(new Date(b.paidAt), "d MMM")}</Pill>
                    ) : b.remindedAt ? (
                      <Pill tone="amber">Reminded</Pill>
                    ) : (
                      <Pill tone="red">Unpaid</Pill>
                    )}
                  </TableCell>
                  <TableCell className="hidden text-xs text-zinc-500 sm:table-cell">
                    <a href={`tel:${b.phone}`} className="hover:underline">
                      {b.phone}
                    </a>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        )}
      </Panel>
    </div>
  );
}
